//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fitness.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FitnessClubs
    {
        public int ClubId { get; set; }
        public string Name { get; set; }
        public string Adress { get; set; }
        public string District { get; set; }
        public string City { get; set; }
        public string Country { get; set; }
        public int ClubOwnerId { get; set; }
    }
}
