//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fitness.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserDetails
    {
        public int UserId { get; set; }
        public byte Age { get; set; }
        public byte UserWeight { get; set; }
        public byte Height { get; set; }
        public string Gender { get; set; }
        public string FatRate { get; set; }
        public string MuscleRate { get; set; }
        public string WaterRate { get; set; }
        public int PersonelTrainerId { get; set; }
    }
}
