//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fitness.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserDetails
    {
        public int UserId { get; set; }
        public Nullable<byte> Age { get; set; }
        public Nullable<byte> UserWeight { get; set; }
        public Nullable<byte> Height { get; set; }
        public string Gender { get; set; }
        public string FatRate { get; set; }
        public string MuscleRate { get; set; }
        public string WaterRate { get; set; }
        public Nullable<int> PersonelTrainerId { get; set; }
    
        public virtual Users Users { get; set; }
    }
}
